### ISSUE TITLE
publish auto-tagger image on GHR

### ISSUE THREAD

**Issue by notdodo** [notdodo/github-actions#32]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by notdodo** [comment]
```yaml
runs:
  using: 'docker'
  image: 'docker://ghcr.io/notdodo/auto-tagger:vXX'
```
